version: "3"

services:
  app1:
    container_name: react-app-build
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
  app2:
    container_name: react-app-dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
