version: "3"

services:
  mariadb1:
    image: mariadb:latest
    container_name: mariadb1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: maxscale
      MYSQL_PASSWORD: my_s3cret
    ports:
      - "3307:3307"
    networks:
      - maxscale_network

  mariadb2:
    image: mariadb:latest
    container_name: mariadb2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: maxscale
      MYSQL_PASSWORD: my_s3cret
    ports:
      - "3308:3307"
    networks:
      - maxscale_network

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    depends_on:
      - mariadb1
      - mariadb2
    ports:
      - "4006:4006"
    volumes:
      - ./maxscale.conf:/etc/maxscale.conf
    networks:
      - maxscale_network

  app1:
    container_name: flask_app_prod
    links:
      - "maxscale"
    build:
      context: ./
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    depends_on:
      - maxscale
    environment:
      HOST: maxscale

  app2:
    container_name: flask_app_build
    links:
      - "maxscale"
    build:
      context: ./
      dockerfile: Dockerfile.build
    ports:
      - "5001:5001"
    depends_on:
      - maxscale
    environment:
      HOST: maxscale

networks:
  maxscale_network:
    driver: bridge
